//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteChat3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussion()
        {
            this.Message = new HashSet<Message>();
            this.UtilisateurDiscussion = new HashSet<UtilisateurDiscussion>();
        }
    
        public int IdDiscussion { get; set; }
        public string TitreDiscussion { get; set; }
        public System.DateTime DateCreationDiscussion { get; set; }
        public string DescriptionDiscussion { get; set; }
        public Nullable<byte> StatutDiscussion { get; set; }
        public int IdTypeDiscussion { get; set; }
        public int IdStatutDiscussion { get; set; }
    
        public virtual StatutDiscussion StatutDiscussion1 { get; set; }
        public virtual TypeDiscussion TypeDiscussion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilisateurDiscussion> UtilisateurDiscussion { get; set; }
    }
}
