//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteChat3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int IdMessage { get; set; }
        public int IdUtilisateur { get; set; }
        public System.DateTime DateEnvoi { get; set; }
        public string TexteMessage { get; set; }
        public int IdDiscussion { get; set; }
        public int IdTon { get; set; }
        public byte StatutMessage { get; set; }
    
        public virtual Discussion Discussion { get; set; }
        public virtual Ton Ton { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
